---
- name: Install pgPool
  yum: name={{ item }} state=installed
  with_items:
   - pgpool-II-93

- name: Setup pgpool extensions
  sudo_user: postgres
  command: psql -f /usr/pgsql-9.3/share/extension/pgpool-recovery.sql template1

- name: Allow the postgres user to run the init script
  template: src=sudoers.j2 dest=/etc/sudoers.d/postgres owner=root group=root mode=0600

- name: Create Postgres pgPool User
  postgresql_user:
    name: pgpool
    password: poolpass
    role_attr_flags: SUPERUSER
  sudo_user: postgres
  when: inventory_hostname == postgres_master

- name: Configure pgPool
  template: src={{ item }}.j2 dest=/etc/pgpool-II-93/{{ item }} mode=0644 owner=root group=root
  with_items:
   - pcp.conf
   - pgpool.conf
   - pool_hba.conf
  notify: restart pgpool

- name: Create directory for pgPool scripts
  file: state=directory path=/usr/local/libexec/pgpool mode=0755 owner=root group=root

- name: Install pgpool scripts
  copy: src={{ item }} dest=/usr/local/libexec/pgpool/{{ item }} mode=0755 owner=root group=root
  with_items:
   - failover.sh

- name: Install pgpool recovery scripts
  copy: src={{ item }} dest=/var/lib/pgsql/9.3/data/{{ item }} mode=0755 owner=root group=root
  with_items:
   - recovery.sh
   - pgpool_remote_start

- name: Configure pgPool
  template: src={{ item }}.j2 dest=/etc/pgpool-II-93/{{ item }} mode=0664 owner=postgres group=postgres
  with_items:
   - pool_passwd
  notify: restart pgpool

- name: Start pgpool
  service: name=pgpool-II-93 state=started enabled=yes

